name: Fast CI - Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  GRADLE_CACHE_DIR: ~/.gradle/caches

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '26.1.10909125'
          cmake-version: '3.22.1'

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # Minimal setup for unit tests
      - name: Setup environment
        run: |
          # Basic Gradle properties
          mkdir -p ~/.gradle
          cat > ~/.gradle/gradle.properties << 'EOL'
          org.gradle.caching=true
          org.gradle.parallel=true
          org.gradle.daemon=false
          # Disable Firebase and Crashlytics in CI
          android.defaults.buildfeatures.buildconfig=true
          firebaseCrashlytics.mappingFileUpdateEnabled=false
          android.enableFirebase=false
          EOL
          
          # Local properties
          echo 'sdk.dir=$ANDROID_HOME' > local.properties
          
          # Create a valid google-services.json with required fields
          mkdir -p app
          cat > app/google-services.json << 'EOL'
          {
            "project_info": {
              "project_number": "000000000000",
              "project_id": "dummy-project-id",
              "storage_bucket": "dummy-bucket.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:000000000000:android:0000000000000000000000",
                  "android_client_info": {
                    "package_name": "com.ronjie.gweather"
                  }
                },
                "api_key": [
                  {
                    "current_key": "dummy-key"
                  }
                ]
              }
            ]
          }
          EOL
          
          # Grant execute permission
          chmod +x gradlew

      # Run unit tests with Firebase disabled
      - name: Run unit tests
        run: |
          ./gradlew testDebugUnitTest --stacktrace --no-daemon -Pandroid.enableFirebase=false

      # Only build debug APK on main branch (skipped in PRs)
      - name: Build debug APK
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon
