name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: '34.0.0'
        platform-version: '34'
        ndk-version: '26.1.10909125'
        cmake-version: '3.22.1'

    # Skip signing for debug builds
    - name: Skip signing
      run: |
        mkdir -p ~/.gradle
        echo 'android.signingConfigs.debug.storePassword=android' > ~/.gradle/gradle.properties
        echo 'android.signingConfigs.debug.keyPassword=android' >> ~/.gradle/gradle.properties
        echo 'android.signingConfigs.debug.keyAlias=androiddebugkey' >> ~/.gradle/gradle.properties
        echo 'android.signingConfigs.debug.storeFile=~/.android/debug.keystore' >> ~/.gradle/gradle.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Disable Firebase and Crashlytics for CI builds
    - name: Configure build for CI
      run: |
        # Create a dummy google-services.json for all build types
        mkdir -p app/src/debug app/src/release
        
        # Create a minimal valid google-services.json
        cat > app/google-services.json << 'EOL'
        {
          "project_info": {
            "project_number": "000000000000",
            "project_id": "dummy-firebase-project",
            "storage_bucket": "dummy-firebase-project.appspot.com"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:000000000000:android:0000000000000000000000",
                "android_client_info": {
                  "package_name": "com.ronjie.gweather"
                }
              },
              "api_key": [
                {
                  "current_key": "dummy-api-key"
                }
              ],
              "services": {
                "appinvite_service": {
                  "status": 1,
                  "other_platform_oauth_client": []
                }
              }
            }
          ],
          "configuration_version": "1"
        }
        EOL
        
        # Disable Firebase and Crashlytics
        echo "android.defaults.buildfeatures.buildconfig=true" >> gradle.properties
        echo "firebaseCrashlytics.mappingFileUpdateEnabled=false" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        
        # Create a local.properties with Firebase disabled
        echo "android.enableFirebase=false" > local.properties

    - name: Build with Gradle
      run: |
        # Build without Firebase and Crashlytics
        ./gradlew clean assembleDebug --stacktrace --info -Pci \
          -Pandroid.enableFirebase=false \
          -PfirebaseCrashlytics.mappingFileUpdateEnabled=false

    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest --stacktrace --info -Pci \
          -Pandroid.enableFirebase=false \
          -PfirebaseCrashlytics.mappingFileUpdateEnabled=false

    - name: Lint check
      run: |
        ./gradlew lintDebug --stacktrace --info -Pci \
          -Pandroid.enableFirebase=false \
          -PfirebaseCrashlytics.mappingFileUpdateEnabled=false

    - name: Assemble debug APK
      if: github.event_name != 'pull_request'
      run: |
        ./gradlew assembleDebug --stacktrace --info -Pci \
          -Pandroid.enableFirebase=false \
          -PfirebaseCrashlytics.mappingFileUpdateEnabled=false
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 5
